# Generated by Django 6.0.3 on 2026-04-28 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingTitle', models.CharField(max_length=100)),
                ('meetingDate', models.DateField()),
                ('meetingTime', models.TimeField()),
                ('meetingPlatform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet')], max_length=30)),
                ('meetingMessage', models.TextField(blank=True)),
                ('scheduleType', models.CharField(choices=[('upcoming', 'Upcoming'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='upcoming', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
